### ISSUE TITLE
How to run the script? 

### ISSUE THREAD

**Issue by aybassiouny** [mcandocia/reddit_posting#1]
On line #20, there's: `apply(out, 1, paste_rev2, collapse=".")`, however 'out' is undefined. Could you elaborate how this script is intended to be run? 

Thanks,

**Comment by mcandocia** [comment]
To run the script, you will need the data. I downloaded it from a source on Google BigQuery: https://bigquery.cloud.google.com/table/fh-bigquery:reddit_comments.2015_05

As for that line, I think it was mistakenly included/I deleted other parts of it earlier. It was likely a test to make sure the function was working properly. I just commented it out and committed the change.
